require:
  - rubocop-rspec
  - rubocop-rails

inherit_gem:
  rubocop-github:
    - config/default.yml
    - config/rails.yml

AllCops:
  NewCops: disable
  SuggestExtensions: false
  Exclude:
    - 'spec/**/*'
    - 'vendor/**/*'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Rails/EnumHash:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

GitHub/RailsControllerRenderPathsExist:
  Enabled: false

Style/TernaryParentheses:
  EnforcedStyle: require_parentheses_when_complex

Lint/MissingSuper:
  Exclude:
    - 'app/components/**/*'
    - 'app/services/**/*'

