version: "3"
services:
  mysql:
    image: mysql:8.2
    environment:
      - "MYSQL_ROOT_PASSWORD=password"
      - "MYSQL_DATABASE=sn_filterable_test"
    ports:
      - 3306:3306

  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sn_filterable_test
